language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t sushangagneja/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sushangagneja/docker-react npm run test